#!/bin/bash

SRCDIR=$HOME/src
PYRDIR=pyroon/roonapi
SUFF="orig"

cd $SRCDIR

[ -f ${PYRDIR}/roonapi.py.${SUFF} ] || {
    SUFF="00"
    [ -f ${PYRDIR}/roonapi.py.${SUFF} ] || {
        echo "Cannot locate backup for file ${PYRDIR}/roonapi.py. Exiting."
        exit 1
    }
}

[ -d ~/src/RoonCommandLine ] || mkdir ~/src/RoonCommandLine
[ -d ~/src/RoonCommandLine/patches ] || mkdir ~/src/RoonCommandLine/patches

OUT=$HOME/src/RoonCommandLine/patches/pyroon-listmedia.patch
rm -f $OUT
touch $OUT
for i in ${PYRDIR}/*.${SUFF}
do
    j=`echo $i | sed -e "s/.${SUFF}//"`
    diff -Naur $i $j >> $OUT
done
