#!/bin/bash

PYDIR=$HOME/.pyenv/versions/3.9.4/lib/python3.9
USERSITE=$PYDIR/site-packages

[ -d $USERSITE/roonapi ] || {
    # First check the Python User Site directory
    USERSITE=`python -m site --user-site`
    if [ -d $USERSITE/roonapi ]
    then
        PYDIR=`echo $USERSITE | awk -F "/site-packages/" ' { print $1 } '`
    else
        # Next check Python's global directories
        SITES=($(python -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
        for site in ${SITES[@]}
        do
            site=`echo $site | sed -e "s/\'//g"`
            [ -d "${site}/roonapi" ] && {
                PYDIR=`echo ${site} | awk -F "/site-packages/" ' { print $1 } '`
                USERSITE=$PYDIR/site-packages
                break
            }
        done
    fi
    [ -d $USERSITE/roonapi ] || {
        echo "Roon API Python module not found. Exiting."
        exit 1
    }
}

cd $PYDIR

[ -d ~/src/RoonCommandLine/patches ] || mkdir ~/src/RoonCommandLine/patches

OUT=$HOME/src/RoonCommandLine/patches/roonapi-listmedia.patch
rm -f $OUT
touch $OUT
for i in site-packages/roonapi/*.orig
do
    j=`echo $i | sed -e "s/.orig//"`
    diff -Naur $i $j >> $OUT
done
