#!/bin/bash

SRCDIR=$HOME/src
RCLDIR=$SRCDIR/RoonCommandLine
PYRDIR=pyroon/roonapi
SUFF="orig"

cd $SRCDIR

[ -f ${PYRDIR}/roonapi.py.${SUFF} ] || {
    SUFF="00"
    [ -f ${PYRDIR}/roonapi.py.${SUFF} ] || {
        echo "Cannot locate backup for file ${PYRDIR}/roonapi.py. Exiting."
        exit 1
    }
}

[ -d ${RCLDIR} ] || mkdir ${RCLDIR}
[ -d ${RCLDIR}/patches ] || mkdir ${RCLDIR}/patches

OUT=${RCLDIR}/patches/pyroon-listmedia.patch
rm -f $OUT
touch $OUT
for i in ${PYRDIR}/*.${SUFF}
do
    j=`echo $i | sed -e "s/.${SUFF}//"`
    diff -Naur $i $j >> $OUT
done
