remote_theme: doctorfree/jekyll-theme-neoman
plugins:
  - jekyll-remote-theme

title: RoonCommandLine
email: ronaldrecord@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Roon Command Line project provides Bash and Python scripts to enable
  command line control of the Roon audio system over a local network.
baseurl: ""
url: "https://rooncommand.dev"
twitter_username: ronrecord
github_username: doctorfree

show_downloads: false
# google_analytics: