#!/bin/bash

ROON=$HOME/Roon
CORE=get_zones.py

[ -d $ROON ] || exit 1

cd $ROON

[ -f $CORE ] || exit 2

# echo "When prompted for authorization, go to a Roon Remote client window,"
# echo "click on 'Settings' then click on 'Extensions' then 'Enable' the extension"

python $CORE
