#!/bin/bash

ROON=$HOME/Roon
ZONECONF=$HOME/.roonzone
LIST=list_playlists.py
PLAYLIST="Bowie Favs"

export PYTHONUSERBASE=/home/doctor/Python3

[ -d $ROON ] || exit 1

cd $ROON

[ -f $LIST ] || exit 2

[ "$1" ] && PLAYLIST="$*"

# Get the zone if it is set
if [ -f ${ZONECONF} ]
then
    . ${ZONECONF}
else
    ROON_ZONE="Living Room"
fi

python $LIST -p "$PLAYLIST" -z "$ROON_ZONE"
