#!/bin/bash

ROON=$HOME/RoonCommandLine
ROONCONF=$HOME/.pyroonconf
LIST=list_zones.py
ZONE=

[ -d $ROON ] || exit 1

cd $ROON

[ -f $LIST ] || exit 2

if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    # Remove leading and trailing spaces in DEFZONE
    DEFZONE="$(echo -e "${DEFZONE}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    set_zone $DEFZONE
    . ${ROONCONF}
fi

[ "$1" ] && ZONE="$*"

# Get the default zone if one is not provided
[ "${ZONE}" ] || {
    if [ "${ROON_ZONE}" ]
    then
        ZONE="${ROON_ZONE}"
    else
        ZONE="${DEFZONE}"
    fi
}

python $LIST -z $ZONE

echo ""
echo "Your configured zone groupings:"
grep ^Group_ $ROON/roon_api.ini
