#!/bin/bash

ROON=$HOME/Roon
ROONCONF=$HOME/.pyroonconf
LIST=list_zones.py
ZONE="Living"

[ -d $ROON ] || exit 1

cd $ROON

[ -f $LIST ] || exit 2

if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $HOME/Roon/roon_api.ini | awk -F '=' ' { print $2 } '`
    set_zone $DEFZONE
    . ${ROONCONF}
fi

[ "$1" ] && ZONE="$*"

python $LIST -z $ZONE
