#!/bin/bash

ROON=$HOME/Roon
ZONECONF=$HOME/.roonzone
LIST=list_zones.py
ZONE="Living"

export PYTHONUSERBASE=/home/doctor/Python3

[ -d $ROON ] || exit 1

cd $ROON

[ -f $LIST ] || exit 2

[ "$1" ] && ZONE="$*"

python $LIST -z $ZONE
