#!/bin/bash

ROON=$HOME/RoonCommandLine
ROONCONF=$HOME/.pyroonconf
LIST=list_playlists.py
PLAYLIST=

[ -d $ROON ] || exit 1

cd $ROON

[ -f $LIST ] || exit 2

[ "$1" ] && PLAYLIST="$*"

# Get the zone if it is set
if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    set_zone $DEFZONE
    . ${ROONCONF}
fi

# Get the default playlist if one is not provided
[ "${PLAYLIST}" ] || {
    PLAYLIST=`grep ^DefaultPlaylist $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    # Remove leading and trailing spaces in PLAYLIST
    PLAYLIST="$(echo -e "${PLAYLIST}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
}

python $LIST -p "$PLAYLIST" -z "$ROON_ZONE"
