#!/bin/bash

ROON=$HOME/RoonCommandLine
ROONCONF=$HOME/.pyroonconf
LIST=list_tags.py
TAG=

[ -d $ROON ] || exit 1

cd $ROON

[ -f $LIST ] || exit 2

[ "$1" ] && TAG="$*"

# Get the zone if it is set
if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    set_zone $DEFZONE
    . ${ROONCONF}
fi

# Get the default album if one is not provided
[ "${TAG}" ] || {
    TAG=`grep ^DefaultTag $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    # Remove leading and trailing spaces in TAG
    TAG="$(echo -e "${TAG}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
}

python $LIST -t "$TAG" -z "$ROON_ZONE"
