#!/bin/bash

ROON=$HOME/Roon
ROONCONF=$HOME/.pyroonconf
LIST=list_genres.py
GENRE="Classical"

[ -d $ROON ] || exit 1

cd $ROON

[ -f $LIST ] || exit 2

[ "$1" ] && GENRE="$*"

# Get the zone if it is set
if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $HOME/Roon/roon_api.ini | awk -F '=' ' { print $2 } '`
    set_zone $DEFZONE
    . ${ROONCONF}
fi

python $LIST -g "$GENRE" -z "$ROON_ZONE"
