#!/bin/bash

ROON=/usr/local/Roon
ROONAPI=${ROON}/api
ROONCONF=${ROON}/etc/pyroonconf
LBIN=${ROON}/bin

for i in *_*
do
    rm -f $LBIN/$i
done
rm -rf ${ROON}

PYTHON_EXE=`type -p python`
[ "${PYTHON_EXE}" ] || PYTHON_EXE=`type -p python3`

[ "${PYTHON_EXE}" ] || {
    echo "Could not locate python executable. Exiting."
    exit 1
}
export PYTHON_EXE

ROON_SITE_DIR=
# Check the global site directories
SITES=($(${PYTHON_EXE} -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
for site in ${SITES[@]}
do
    [ -d ${site}/roonapi ] && {
        ROON_SITE_DIR=${site}/roonapi
        break
    }
done

rm -f $ROONCONF

if [ "$ROON_SITE_DIR" ]
then
    # Roll back the Python Roon API patch if it was applied
    cd $ROON_SITE_DIR
    for i in *.orig
    do
        [ "$i" == "*.orig" ] && continue
        j=`echo $i | sed -e "s/.orig//"`
        mv $i $j
    done
else
    echo "Could not locate the roonapi Python module installation directory"
    echo "Python Roon API patch not reversed."
fi

echo ""
echo "Roon Command Line uninstalled"
