#!/bin/bash

ROON=$HOME/Roon
MUTE=mute_zone.py
ZONE="Living Room"

export PYTHONUSERBASE=/home/doctor/Python3

[ -d $ROON ] || exit 1

cd $ROON

[ -f $MUTE ] || exit 2

[ "$1" ] && ZONE="$1"

python $MUTE -z "$ZONE"
