#!/bin/bash

ROON=$HOME/Roon
NEXT=next_track.py
ZONE="Living Room"

export PYTHONUSERBASE=/home/doctor/Python3

[ -d $ROON ] || exit 1

cd $ROON

[ -f $NEXT ] || exit 2

[ "$1" ] && ZONE="$1"

python $NEXT -z "$ZONE"
