#!/bin/bash

ROON=$HOME/RoonCommandLine
ROONCONF=$HOME/.pyroonconf
PLAY=play_playlist.py
PLAYLIST="Bowie Favs"

[ -d $ROON ] || exit 1

cd $ROON

[ -f $PLAY ] || exit 2

[ "$1" ] && PLAYLIST="$*"

# Get the zone if it is set
if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    set_zone $DEFZONE
    . ${ROONCONF}
fi

python $PLAY -p "$PLAYLIST" -z "$ROON_ZONE"
