#!/bin/bash

ROON=$HOME/Roon
ZONECONF=$HOME/.roonzone
PLAY=play_genre.py
GENRE="Classical"

export PYTHONUSERBASE=/home/doctor/Python3

[ -d $ROON ] || exit 1

cd $ROON

[ -f $PLAY ] || exit 2

[ "$1" ] && GENRE="$*"

# Get the zone if it is set
if [ -f ${ZONECONF} ]
then
    . ${ZONECONF}
else
    ROON_ZONE="Living Room"
fi

python $PLAY -g "$GENRE" -z "$ROON_ZONE"
