#!/bin/bash

ROON=$HOME/RoonCommandLine
ROONCONF=$HOME/.pyroonconf
PLAY=play_tag.py
TAG="Prog"

[ -d $ROON ] || exit 1

cd $ROON

[ -f $PLAY ] || exit 2

[ "$1" ] && TAG="$*"

# Get the zone if it is set
if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    set_zone $DEFZONE
    . ${ROONCONF}
fi

python $PLAY -t "$TAG" -z "$ROON_ZONE"
