#!/bin/bash

ROON=$HOME/RoonCommandLine
ROONCONF=$HOME/.pyroonconf
PLAY=play_genre.py
GENRE=

[ -d $ROON ] || exit 1

cd $ROON

[ -f $PLAY ] || exit 2

[ "$1" ] && GENRE="$*"

# Get the zone if it is set
if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    set_zone $DEFZONE
    . ${ROONCONF}
fi

# Get the default genre if one is not provided
[ "${GENRE}" ] || {
    GENRE=`grep ^DefaultGenre $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    # Remove leading and trailing spaces in GENRE
    GENRE="$(echo -e "${GENRE}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
}

python $PLAY -g "$GENRE" -z "$ROON_ZONE"
