#!/bin/bash

ROON=$HOME/RoonCommandLine
ROONCONF=$HOME/.pyroonconf
PLAY=play_artist.py
ARTIST=

[ -d $ROON ] || exit 1

cd $ROON

[ -f $PLAY ] || exit 2

[ "$1" ] && ARTIST="$*"

# Get the zone if it is set
if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    set_zone $DEFZONE
    . ${ROONCONF}
fi

# Get the default artist if one is not provided
[ "${ARTIST}" ] || {
    ARTIST=`grep ^DefaultArtist $ROON/roon_api.ini | awk -F '=' ' { print $2 } '`
    # Remove leading and trailing spaces in ARTIST
    ARTIST="$(echo -e "${ARTIST}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
}

python $PLAY -a "$ARTIST" -z "$ROON_ZONE"
