#!/bin/bash
#
# roon - frontend shell script to issue remote commands to Roon via SSH and the Roon API
#
#  Copyright 2021, Ronald Joe Record
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
# Edit these two settings
#   The IP address of the system on which the Python Roon API is installed
server="XX.X.X.XXX"
#   The username that has public key authorized SSH access to the Python Roon API system
user="SSH_USERNAME"

album=
artist=
comm=
albumlist=
artistlist=
genrelist=
playlistlist=
zonelist=
playlist=
radio=
search=
tag=
zone=

usage() {
  printf "\nUsage: roon -A album -a artist -g genre -l [albums|artists|genres|playlists|zones] -s search -p playlist -t tag -z zone\n\t-c [play|pause|stop|next|previous|shuffle|unshuffle|repeat|unrepeat|mute|unmute]\n\t-r -u"
  printf "\n\tWhere:\n\t\t-A album selects an album to play"
  printf "\n\t\t-a artist selects an artist to play"
  printf "\n\t\t-g genre selects a genre to play"
  printf "\n\t\t-p playlist selects a playlist to play"
  printf "\n\t\t-l [albums|artists|genres|playlists|zones] indicates list albums, artists, genres, playlists, or Roon zones"
  printf "\n\t\t-s search specifies a term to search for in the lists retrieved with -l"
  printf "\n\t\t-r indicates play Radio Paradise"
  printf "\n\t\t-t tag selects an tag to play (not yet working)"
  printf "\n\t\t-z zone selects the Roon Zone in which to play"
  printf "\n\t\t-c [play|pause|playpause|stop|next|previous|shuffle|unshuffle|repeat|unrepeat|mute|unmute]"
  printf "\n\t\t\tissues the command in the selected zone"
  printf "\n\n\tExample invocations"
  printf "\n\t\tPlay artist:"
  printf "\n\t\t\troon -a \"Deep Purple\""
  printf "\n\t\tPlay artist in specified zone:"
  printf "\n\t\t\troon -a \"Jethro Tull\" -z \"Living Room\""
  printf "\n\t\tPlay genre:"
  printf "\n\t\t\troon -g Classical"
  printf "\n\t\tPlay playlist:"
  printf "\n\t\t\troon -p \"Bowie Favs\""
  printf "\n\t\tPlay next track:"
  printf "\n\t\t\troon -c next"
  printf "\n\t\tStop play in specified zone:"
  printf "\n\t\t\troon -c stop -z Kitchen"
  printf "\n\t\tMute a specified zone:"
  printf "\n\t\t\troon -c mute -z \"Living Room\""
  printf "\n\t\tList all playlists containing the string 'Best':"
  printf "\n\t\t\troon -l playlists -s \"Best\"\n\n"
  exit 1
}

[ "$1" ] || usage

while getopts A:a:g:p:t:z:c:l:s:ru flag; do
    case $flag in
        A)
            album="$OPTARG"
            ;;
        a)
            artist="$OPTARG"
            ;;
        g)
            genre="$OPTARG"
            ;;
        p)
            playlist="$OPTARG"
            ;;
        t)
            tag="$OPTARG"
            ;;
        z)
            zone="$OPTARG"
            ;;
        c)
            comm="$OPTARG"
            ;;
        l)
            listname="$OPTARG"
            if [ "$listname" == "albums" ] || [ "$listname" == "album" ]
            then
                albumlist=1
            elif [ "$listname" == "artists" ] || [ "$listname" == "artist" ]
            then
                artistlist=1
            elif [ "$listname" == "genres" ] || [ "$listname" == "genre" ]
            then
                genrelist=1
            elif [ "$listname" == "playlists" ] || [ "$listname" == "playlist" ]
            then
                playlistlist=1
            elif [ "$listname" == "zones" ] || [ "$listname" == "zone" ]
            then
                zonelist=1
            else
                echo "Unknown list type: $listname"
                usage
            fi

            ;;
        r)
            radio=1
            ;;
        s)
            search="$OPTARG"
            ;;
        u)
            usage
            ;;
    esac
done

[ "$search" ] || search="all"

# Set Zone
[ "$zone" ] && ssh $user@$server "bash -l -c \"set_zone $zone\""

[ "$albumlist" ] && ssh $user@$server "bash -l -c \"list_albums $search\""
[ "$artistlist" ] && ssh $user@$server "bash -l -c \"list_artists $search\""
[ "$genrelist" ] && ssh $user@$server "bash -l -c \"list_genres $search\""
[ "$playlistlist" ] && ssh $user@$server "bash -l -c \"list_playlists $search\""
[ "$zonelist" ] && ssh $user@$server "bash -l -c \"list_zones $search\""
[ "$album" ] && ssh $user@$server "bash -l -c \"play_album $album\""
[ "$artist" ] && ssh $user@$server "bash -l -c \"play_artist $artist\""
[ "$genre" ] && ssh $user@$server "bash -l -c \"play_genre $genre\""
[ "$playlist" ] && ssh $user@$server "bash -l -c \"play_playlist $playlist\""
[ "$tag" ] && ssh $user@$server "bash -l -c \"play_tag $tag\""
[ "$radio" ] && ssh $user@$server "bash -l -c play_rp"

[ "$comm" ] && {
    case "$comm" in
    "shuffle"|"unshuffle"|"repeat"|"unrepeat"|"mute"|"unmute"|"next"|"previous"|"play"|"pause"|"stop"|"playpause")
        ssh $user@$server "bash -l -c \"zone_command -c ${comm}\""
        ;;
    *)
        echo "Unrecognized Roon command: $comm"
        usage
        ;;
    esac
}

exit 0
