#!/bin/bash
#
# roon - frontend shell script to issue remote commands to Roon via SSH and the Roon API
#
# Example invocations
# Play artist:
#    roon -a "Deep Purple"
# Play genre:
#    roon -g Classical
# Play next track:
#    roon -c next
# Play tag not yet working

server="10.0.1.22"
user="doctor"
list=
zone=
radio=
comm=
artist=
tag=

usage() {
  printf "\nUsage: roon -a artist -g genre -t tag -z zone -c [stop|next|previous|mute|unmute] -l -r -u"
  printf "\n\tWhere:\n\t\t-a artist selects an artist to play"
  printf "\n\t\t-g genre selects a genre to play"
  printf "\n\t\t-l indicates list Roon Zones"
  printf "\n\t\t-r indicates play Radio Paradise"
  printf "\n\t\t-t tag selects an tag to play (not yet working)"
  printf "\n\t\t-z zone selects the Roon Zone in which to play"
  printf "\n\t\t-c [stop|next|previous|mute|unmute] issues the specified command"
  printf "\n\n\tExample invocations"
  printf "\n\t\tPlay artist:"
  printf "\n\t\t\troon -a \"Deep Purple\""
  printf "\n\t\tPlay artist in specified zone:"
  printf "\n\t\t\troon -a \"Jethro Tull\" -z \"Living Room\""
  printf "\n\t\tPlay genre:"
  printf "\n\t\t\troon -g Classical"
  printf "\n\t\tPlay next track:"
  printf "\n\t\t\troon -c next"
  printf "\n\t\tStop play in specified zone:"
  printf "\n\t\t\troon -c stop -z Kitchen"
  printf "\n\t\tMute a specified zone:"
  printf "\n\t\t\troon -c mute -z \"Living Room\"\n\n"
  exit 1
}

[ "$1" ] || usage

while getopts a:g:t:z:c:lru flag; do
    case $flag in
        a)
            artist="$OPTARG"
            ;;
        g)
            genre="$OPTARG"
            ;;
        t)
            tag="$OPTARG"
            ;;
        z)
            zone="$OPTARG"
            ;;
        c)
            comm="$OPTARG"
            ;;
        l)
            list=1
            ;;
        r)
            radio=1
            ;;
        u)
            usage
            ;;
    esac
done

# Set Zone
[ "$zone" ] && ssh $user@$server "bash -l -c \"set_zone $zone\""

[ "$list" ] && ssh $user@$server "bash -l -c list_zones"
[ "$artist" ] && ssh $user@$server "bash -l -c \"play_artist $artist\""
[ "$genre" ] && ssh $user@$server "bash -l -c \"play_genre $genre\""
[ "$tag" ] && ssh $user@$server "bash -l -c \"play_tag $tag\""
[ "$radio" ] && ssh $user@$server "bash -l -c play_rp"

[ "$comm" ] && {
    case "$comm" in
    "mute" | "unmute" | "stop")
        ssh $user@$server "bash -l -c \"${comm}_zone $zone\""
        ;;
    "next" | "previous")
        ssh $user@$server "bash -l -c \"${comm}_track $zone\""
        ;;
    *)
        echo "Unrecognized Roon command: $comm"
        usage
        ;;
    esac
}

exit 0
