#!/bin/bash

ROONCONF=$HOME/.pyroonconf

# Locate Python user base
USERSITE=`python -m site --user-site`
# First check the Python user site dir
if [ -d $USERSITE/roonapi ]
then
    PYTHONUSERBASE=`echo $USERSITE | awk -F "/lib/" ' { print $1 } '`
    base=`basename $PYTHONUSERBASE`
    SITEDIR=`echo $USERSITE | awk -F "/${base}/" ' { print $2 } '`
else
    # Check the global site directories
    SITES=($(python -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
    for site in ${SITES[@]}
    do
        [ -d ${site}/roonapi ] && {
            PYTHONUSERBASE=`echo ${site} | awk -F "/lib/" ' { print $1 } '`
            base=`basename $PYTHONUSERBASE`
            SITEDIR=`echo ${site} | awk -F "/${base}/" ' { print $2 } '`
            break
        }
    done
fi

[ "$PYTHONUSERBASE" ] || PYTHONUSERBASE="$HOME/Python3"

[ "$1" ] && ZONE="$*"

if [ -f $ROONCONF ]
then
    grep -v ^ROON_ZONE $ROONCONF > /tmp/roonconf$$
    echo "ROON_ZONE=\"$ZONE\"" >> /tmp/roonconf$$
    cp /tmp/roonconf$$ $ROONCONF
    rm -f /tmp/roonconf$$
    grep PYTHONUSERBASE $ROONCONF > /dev/null || {
        echo "export PYTHONUSERBASE=$PYTHONUSERBASE" >> $ROONCONF
    }
else
    echo "ROON_ZONE=\"$ZONE\"" > $ROONCONF
    echo "export PYTHONUSERBASE=$PYTHONUSERBASE" >> $ROONCONF
fi
