#!/bin/bash

ROON=$HOME/Roon
STOP=stop_zone.py
ZONE="Living Room"

export PYTHONUSERBASE=/home/doctor/Python3

[ -d $ROON ] || exit 1

cd $ROON

[ -f $STOP ] || exit 2

[ "$1" ] && ZONE="$1"

python $STOP -z "$ZONE"
