#!/bin/bash
#
# shellcheck disable=SC1090,SC2220,SC2207,SC2068,SC2001

uninstall() {
  LOCAL="/usr/local"
  APPL=${LOCAL}/share/applications
  DOC=${LOCAL}/share/doc
  ROON=${LOCAL}/Roon
  ROONBIN=${ROON}/bin

  [ -d /usr/local/bin ] && {
    cd /usr/local/bin || exit 1
    for command in "${ROONBIN}"/*
    do
      [ "${command}" == "${ROONBIN}/*" ] && continue
      b=$(basename "${command}")
      [ -L "$b" ] && {
        /bin/ls -l "$b" | grep ${ROON} > /dev/null && sudo rm -f "$b"
      }
    done
  }

  sudo rm -rf ${ROON}
  sudo rm -rf ${DOC}/RoonCommandLine
  sudo rm -f ${APPL}/rooncommand.desktop

  ROON_SITE_DIR=
  # Check the global site directories
  have_python3=$(type -p python3)
  if [ "${have_python3}" ]
  then
    SITES=($(sudo python3 -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
  else
    SITES=($(sudo python -c 'import site; print(site.getsitepackages())' | tr -d '[],'))
  fi
  for site in ${SITES[@]}
  do
    site=$(echo "$site" | sed -e "s/'//g")
    [ -d "${site}"/roonapi ] && {
      ROON_SITE_DIR=${site}/roonapi
      break
    }
  done

  if [ "$ROON_SITE_DIR" ]
  then
    # Roll back the Python Roon API patch if it was applied
    cd "$ROON_SITE_DIR" || exit 1
    for i in *.orig
    do
      [ "$i" == "*.orig" ] && continue
      j=$(echo "$i" | sed -e "s/.orig//")
      sudo mv "$i" "$j"
    done
  else
    echo "Could not locate the roonapi Python module installation directory"
    echo "Python Roon API patch not reversed."
  fi

  # Don't uninstall roonapi Python module, they might be using it for something else
  # if [ "${have_python3}" ]
  # then
  #     sudo python3 -m pip uninstall roonapi -y
  # else
  #     sudo python -m pip uninstall roonapi -y
  # fi

  echo ""
  echo "RoonCommandLine uninstalled"
}

have_fade=$(type -p roon_fade)
[ "${have_fade}" ] && roon_fade off

plat=$(uname -s)
if [ "$plat" == "Darwin" ]
then
  uninstall
else
  debian=
  have_apt=$(type -p apt)
  have_dpkg=$(type -p dpkg)
  have_rpm=$(type -p rpm)
  have_yum=$(type -p yum)
  [ -f /etc/os-release ] && . /etc/os-release
  [ "${ID_LIKE}" == "debian" ] && debian=1
  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1

  PKG=rooncommandline
  [ "${debian}" ] || PKG=RoonCommandLine

  if [ "${debian}" ]
  then
    if [ "${have_apt}" ]
    then
      sudo apt remove "${PKG}" -y > /dev/null 2>&1
    else
      if [ "${have_dpkg}" ]
      then
        sudo dpkg -r "${PKG}" > /dev/null 2>&1
      else
        echo "Cannot locate either apt or dpkg to remove. Skipping."
      fi
    fi
  else
    if [ "${have_yum}" ]
    then
      sudo yum remove "${PKG}" > /dev/null 2>&1
    else
      if [ "${have_rpm}" ]
      then
        sudo rpm -e "${PKG}" > /dev/null 2>&1
      else
        echo "Cannot locate either yum or rpm to remove. Skipping."
      fi
    fi
  fi
  uninstall
fi
