#!/bin/bash

ROON=$HOME/Roon
UNMUTE=unmute_zone.py
ZONE="Living Room"

export PYTHONUSERBASE=/home/doctor/Python3

[ -d $ROON ] || exit 1

cd $ROON

[ -f $UNMUTE ] || exit 2

[ "$1" ] && ZONE="$1"

python $UNMUTE -z "$ZONE"
