#!/bin/bash

ROON=$HOME/Roon
ZONECONF=$HOME/.roonzone
UNMUTE=unmute_zone.py

export PYTHONUSERBASE=/home/doctor/Python3

[ -d $ROON ] || exit 1

cd $ROON

[ -f $UNMUTE ] || exit 2

# Get the zone if it is set
if [ -f ${ZONECONF} ]
then
    . ${ZONECONF}
else
    ROON_ZONE="Living Room"
fi
[ "$1" ] && ROON_ZONE="$*"

python $UNMUTE -z "$ROON_ZONE"
