#!/bin/bash

ROON=$HOME/Roon
ROONCONF=$HOME/.pyroonconf
SCRIPT=zone_command.py
COMMAND="play"

[ -d $ROON ] || exit 1

cd $ROON

[ -f $SCRIPT ] || exit 2

# Get the zone if it is set
if [ -f ${ROONCONF} ]
then
    . ${ROONCONF}
else
    DEFZONE=`grep ^DefaultZone $HOME/Roon/roon_api.ini | awk -F '=' ' { print $2 } '`
    set_zone $DEFZONE
    . ${ROONCONF}
fi

# Parse the arguments to get the command and zone
while getopts "c:z:" flag; do
    case $flag in
        c)
            COMMAND="$OPTARG"
            ;;
        z)
            ROON_ZONE="$OPTARG"
            ;;
    esac
done

python $SCRIPT -c "$COMMAND" -z "$ROON_ZONE"
