#!/bin/bash
# prerm script for rooncommandline
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    remove)
        if [ -x /usr/local/Roon/etc/preremove ]
        then
            /usr/local/Roon/etc/preremove
        fi
        rm -rf /usr/local/Roon/venv
    ;;
    upgrade|deconfigure)
        ROONETC=/usr/local/Roon/etc
        ROONCONF=${ROONETC}/pyroonconf
        ROON_INI=${ROONETC}/roon_api.ini
        [ -f ${ROON_INI} ] && {
            cp ${ROON_INI} /tmp/_roon_api_ini_.save
        }
        [ -f ${ROONCONF} ] && {
            cp ${ROONCONF} /tmp/_pyroonconf_.save
        }
        if [ -x /usr/local/Roon/etc/preremove ]
        then
            /usr/local/Roon/etc/preremove
        fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
