#!/bin/bash

plist_name="$1"

[ -f ${plist_name}.plist ] || {
    echo "Cannot locate ${plist_name}.plist - exiting."
    exit 1
}

echo "Converting ${plist_name}.plist from binary to XML format"
plutil -convert xml1 ${plist_name}.plist
