#!/usr/bin/env bash

ROON=/usr/local/Roon
PIPARGS="--no-cache-dir --upgrade --force-reinstall"

if [[ $EUID -eq 0 ]]
then
  SUDO=
else
  SUDO=sudo
fi

export PATH=$PATH:/usr/local/bin
if [ -x /home/linuxbrew/.linuxbrew/bin/brew ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
else
  if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  else
    [ -x /usr/local/bin/brew ] && eval "$(/usr/local/bin/brew shellenv)"
  fi
fi

have_python3=$(type -p python3)
if [ "${have_python3}" ]; then
  PYTHON=python3
else
  have_python=$(type -p python)
  if [ "${have_python}" ]; then
    PYTHON=python
  else
    echo "ERROR: unable to locate Python executable in PATH"
    exit 1
  fi
fi

[ -d ${ROON} ] || {
  echo "ERROR: RoonCommandLine not installed."
  exit 1
}

# Remove previously installed Python virtual environment
${SUDO} rm -rf ${ROON}/venv

# Create the RoonCommandLine Python virtual environment
${SUDO} ${PYTHON} -m venv ${ROON}/venv >/dev/null 2>&1
# Use the RoonCommandLine Python virtual environment
[ -f ${ROON}/venv/bin/activate ] && source ${ROON}/venv/bin/activate
[[ ":$PATH:" == *":/usr/local/Roon/venv/bin:"* ]] || {
  export PATH=/usr/local/Roon/venv/bin:${PATH}
}
[ -x ${ROON}/venv/bin/python ] && export PYTHON=${ROON}/venv/bin/python
# Make sure we have pip installed
${SUDO} ${PYTHON} -m ensurepip --upgrade >/dev/null 2>&1
[ -x ${ROON}/venv/bin/pip ] || {
  PYOUT="/tmp/get-pip$$.py"
  PYURL="https://bootstrap.pypa.io/get-pip.py"
  have_curl=$(type -p curl)
  if [ "${have_curl}" ]; then
    curl -sSL -o ${PYOUT} ${PYURL}
  else
    have_wget=$(type -p wget)
    if [ "${have_wget}" ]; then
      wget -q -O ${PYOUT} ${PYURL}
    else
      echo "WARNING: Unable to locate curl or wget to download pip install script"
    fi
  fi
  if [ -f ${PYOUT} ]; then
    ${SUDO} ${PYTHON} ${PYOUT}
  else
    echo "WARNING: pip install script not found"
  fi
  rm -f ${PYOUT}
}
[ -x ${ROON}/venv/bin/pip ] || {
  echo "WARNING: ${ROON}/venv/bin/pip not found or not executable"
}

${SUDO} ${PYTHON} -m pip install ${PIPARGS} roonapi >/dev/null 2>&1
${SUDO} ${PYTHON} -m pip install ${PIPARGS} rich-cli >/dev/null 2>&1
